services:
  # Backend Node.js Service
  - type: web
    name: donkey-game-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    
  # Frontend Static Site
  - type: static
    name: donkey-game-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    plan: free
    buildFilter:
      paths:
      - client/**
    envVars:
      - key: VITE_SERVER_URL
        fromService:
          type: web
          name: donkey-game-backend
          property: host